seed: 42
device: "cpu"
data:
  path: "data/sample/synth_prices.csv"
  window: 32
  horizon: 1
  train_split: 0.8
model:
  input_dim: 5
  hidden_dim: 128
  depth: 4
physics:
  kappa: 1.5
  theta: 0.04
  sigma_v: 0.25
  dt: 1.0
  lambda_phys: 5.0
  lambda_tv: 0.1
train:
  batch_size: 64
  lr: 1e-3
  epochs: 10
  ckpt_dir: "runs"
  ckpt_name: "last.pt"
  log_interval: 50
